//CLASSE RESPONSÁVEL PARA FAZER OS TRATAMENTOS NECESSÁRIOS DO 
class DateHelper{


	//SEMPRE QUANDO O PROGRAMADOR TENTAR INSTANCIAR O DateHelper É LANÇADO UM ERRO NO CONSOLE	
	constructor(){

		throw new Error('DateHelper não pode ser instanciada');
	}


	//MÉTODOS ESTÁTICOS FAZEM COM QUE SEJA POSSÍVEL A UTILIZAÇÃO DOS MESMOS SEM A NECESSIDADE
	//DE SE INSTANCIAR O OBJETO DA CLASSE
	static dataParaTexto(data){
		//TEM QUE SOMAR + 1 NO MÊS PQ O Date RETORNA O NÚMERO DO MÊS -1
		//AI COMEÇA DO 0 AO 12
		//NECESSITA SER ENTRE OS PARÊNTESIS, POIS O JAVASCRIPT CONCATENA SE NÃO INDICAR A OPERAÇÃO PRIMEIRO
		/*return data.getDate()
		+ '/' + (data.getMonth() + 1)
		+ '/' + data.getFullYear();
		*/

		//EXISTE OUTRA FORMA PARA FAZER ESSA CONCATENAÇÃO QUE É POR MEIO DO TEMPLATE STRING
		//O TEMPLATE STRING VEIO COM O ECMASCRIPT 2015
		return `${data.getDate()}/${data.getMonth()+1}/${data.getFullYear()}`;		
	}

	//MÉTODOS ESTÁTICOS FAZEM COM QUE SEJA POSSÍVEL A UTILIZAÇÃO DOS MESMOS SEM A NECESSIDADE
	//DE SE INSTANCIAR O OBJETO DA CLASSE
	static textoParaData(texto){

		//SE VOCÊ ENVIAR UM ARRAY COM ['ano', 'mes', 'dia']
		//VOCÊ CONSEGUE INSTANCIAR UMA DATA
		//DIVIDINDO A STRING COM O - ELE RETORNA UM ARRAY
		//let data = new Date(this._inputData.value.split('-'));
		//AO INVÉS DE UTILIZAR O split('-') É POSSÍVEL UTILIZAR O REPLACE, POIS
		//O new Date() NA VERDADE QUANDO RECEBE UM ARRAY ELE FAZ UM join(',')
		//JUNTANDO TUDO EM UMA STRING
		//TROCA TUDO POR - POR ,
		//ELE TAMBÉM ACEITA RECEBER NÚMEROS, MAS O MÊS PRECISA PASSAR DE 0 A 11
		//let data = new Date(this._inputData.value.replace('/-/g', ','));


		//EXPRESSÃO REGULAR QUE TESTA SE O TEXTO POSSUI ESSE PADRÃO
		//SE RETORNAR FALSO, OU SEJA SE NÃO É IGUAL
		if(!/\d{4}-\d{2}-\d{2}/.test(texto)) 
			throw new Error('Deve estar no formato aaaa-mm-dd');

		//FAZENDO A CONVERSÃO COM O PARADIGMA FUNCIONAL
		//NO ES6, TEMOS O RECURSO DE SPREAD OPERATOR, QUE É OS TRÊS PONTOS
		//COM O SPREAD OPERATOR, INDICAMOS QUE O ARRAY SERÁ DESMEMBRADO - E O PRIMEIRO ITEM DO ARRAY,
		//E CADA PARÂMETRO DO Date SERÁ POSICIONADO NA MESMA ORDEM DO CONSTRUTOR
		//MAP INTERAGE COM TODOS OS VALORES DO ARRAY PASSANDO O item COM CADA VALOR E SEU INDICE
		//ARROW FUNCTION (=>) UTILIZADA AO INVÉS DE DIGITAR function(), É MENOS VERBOSO
		//QUANDO SE TEM UMA ÚNICA INSTRUÇÃO NA ARROW FUNCTION É POSSÍVEL TIRAR AS CHAVES E A PALAVRA return
		//COMO A DATA TEM 3 POSIÇÕES DE 0 A 3
		//É EVITADO DE FAZER UM if
		//PQ O MÊS É O INDICE 1 E O RESTO DE 1 COM 2 É 1 E AÍ SÓ SUBTRAI O MÊS
		return new Date(...texto.split('-').map((item, indice) => item - indice % 2));
	}

}